version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.9
    commands: 
      - pip install --upgrade pip aws-sam-cli
      - sam --version
      - docker info
      - pip install cfn-lint
  build:
    commands:
      # - cfn-lint -t template.yaml
      - echo Pre Build started on `date`
      - echo Current Working Dir `pwd`
      - echo files `ls`
      - sam build --use-container
      - echo Build completed on `date`
  post_build:
    commands:
      - sam package --template-file .aws-sam/build/template.yaml --s3-bucket $S3_BUCKET --s3-prefix return-prediction-model --output-template-file packaged-template.yaml
artifacts:
  files:
    - packaged-template.yaml